/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as RSlugRouteImport } from './routes/r.$slug'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardQrRouteImport } from './routes/dashboard.qr'
import { Route as DashboardLinksRouteImport } from './routes/dashboard.links'
import { Route as DashboardDomainsRouteImport } from './routes/dashboard.domains'
import { Route as DashboardAnalyticsRouteImport } from './routes/dashboard.analytics'
import { Route as DashboardAdminRouteImport } from './routes/dashboard.admin'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const RSlugRoute = RSlugRouteImport.update({
  id: '/r/$slug',
  path: '/r/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardQrRoute = DashboardQrRouteImport.update({
  id: '/qr',
  path: '/qr',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLinksRoute = DashboardLinksRouteImport.update({
  id: '/links',
  path: '/links',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDomainsRoute = DashboardDomainsRouteImport.update({
  id: '/domains',
  path: '/domains',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAnalyticsRoute = DashboardAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdminRoute = DashboardAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/domains': typeof DashboardDomainsRoute
  '/dashboard/links': typeof DashboardLinksRoute
  '/dashboard/qr': typeof DashboardQrRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/r/$slug': typeof RSlugRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/domains': typeof DashboardDomainsRoute
  '/dashboard/links': typeof DashboardLinksRoute
  '/dashboard/qr': typeof DashboardQrRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/r/$slug': typeof RSlugRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/domains': typeof DashboardDomainsRoute
  '/dashboard/links': typeof DashboardLinksRoute
  '/dashboard/qr': typeof DashboardQrRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/r/$slug': typeof RSlugRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/dashboard/admin'
    | '/dashboard/analytics'
    | '/dashboard/domains'
    | '/dashboard/links'
    | '/dashboard/qr'
    | '/dashboard/settings'
    | '/r/$slug'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard/admin'
    | '/dashboard/analytics'
    | '/dashboard/domains'
    | '/dashboard/links'
    | '/dashboard/qr'
    | '/dashboard/settings'
    | '/r/$slug'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/dashboard'
    | '/dashboard/admin'
    | '/dashboard/analytics'
    | '/dashboard/domains'
    | '/dashboard/links'
    | '/dashboard/qr'
    | '/dashboard/settings'
    | '/r/$slug'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  RSlugRoute: typeof RSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/r/$slug': {
      id: '/r/$slug'
      path: '/r/$slug'
      fullPath: '/r/$slug'
      preLoaderRoute: typeof RSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/qr': {
      id: '/dashboard/qr'
      path: '/qr'
      fullPath: '/dashboard/qr'
      preLoaderRoute: typeof DashboardQrRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/links': {
      id: '/dashboard/links'
      path: '/links'
      fullPath: '/dashboard/links'
      preLoaderRoute: typeof DashboardLinksRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/domains': {
      id: '/dashboard/domains'
      path: '/domains'
      fullPath: '/dashboard/domains'
      preLoaderRoute: typeof DashboardDomainsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/analytics': {
      id: '/dashboard/analytics'
      path: '/analytics'
      fullPath: '/dashboard/analytics'
      preLoaderRoute: typeof DashboardAnalyticsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin': {
      id: '/dashboard/admin'
      path: '/admin'
      fullPath: '/dashboard/admin'
      preLoaderRoute: typeof DashboardAdminRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardAdminRoute: typeof DashboardAdminRoute
  DashboardAnalyticsRoute: typeof DashboardAnalyticsRoute
  DashboardDomainsRoute: typeof DashboardDomainsRoute
  DashboardLinksRoute: typeof DashboardLinksRoute
  DashboardQrRoute: typeof DashboardQrRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAdminRoute: DashboardAdminRoute,
  DashboardAnalyticsRoute: DashboardAnalyticsRoute,
  DashboardDomainsRoute: DashboardDomainsRoute,
  DashboardLinksRoute: DashboardLinksRoute,
  DashboardQrRoute: DashboardQrRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRouteWithChildren,
  RSlugRoute: RSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
